### ISSUE TITLE
(Enhancement) 'List of Timeseries for Selected Marker': add possibilities to select all timeseries in the list or on the page and to remove selection

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#47]
_Steps to reproduce:_

1 Navigate to http://qa-hiswebclient.azurewebsites.net/
2 Chose the area for example 9103 sq km
3 Click 'Search Map'
4 Click the marker on the map

_Result:_
it's impossible to choose all timeseries or to remove the selection of several timeseries at once. To select/disselect items the user has to click each item. It's possible to choose only Top 25 (see file attached 53.png)

_Expected result:_
We suggest you to add possibilities to select all timeseries in the list or on the page and to remove selection of several items

**Comment by Stref** [comment]
![53](https://cloud.githubusercontent.com/assets/13001938/8382827/46f96de8-1c3e-11e5-9dd7-8aaa6c9cef54.png)

**Comment by ghost** [comment]
BCC - 30-Jun-2015 - Recommend: Reject

By design, the application limits the selection of time series for any one location to a maximum of 25.   

Please note: The 'Select Top 25' option provides 'deselect all'  functionality as a 'side-effect'.  If the user clicks the 'Select Top 25' check box, the application removes all previous selections, if any, and then selects the first 25 time series in the currently sorted order.  If the user then unclicks the checkbox, the application clears the selection.

**Comment by ghost** [comment]
Review Meeting Findings - 01-Jul-2015

For First Release
Add 'clear selections' button - enable whenever any selections are made;  disable whenever no selections are made...

**Comment by ghost** [comment]
BCC - 06-Jul-2015 -

Implemented all first release changes specified by review meeting...

**Comment by Stref** [comment]
Validated on build from 13.08.2015
Realised according to comment above

> For First Release
> Add 'clear selections' button - enable whenever any selections are made; disable whenever no 
> selections are made...
> ![144](https://cloud.githubusercontent.com/assets/13001938/9249681/fdf2fdb4-41cf-11e5-8049-d6d6bece82c4.png)

Closed
